# Shared by scripts/gen-db-types.sh and scripts/check-db-types.sh (G5). Wave 8
# (docs/plans/WAVE8_GENERATED_TYPES_PLAN.md, F0 steps 1 + 3). Sourced, not run.
#
# The two preconditions that make `supabase gen types --local` trustworthy:
#   (a) the local DB has applied EXACTLY this checkout's migrations — the DB is
#       shared by every worktree, so a sibling's db/… migration can be applied
#       locally and land in the output while prod lacks it (§7.347);
#   (b) the local CLI is the version CI pins — gen output changes between CLI
#       versions, so a mismatch is a diff with no schema change.
# Never fork these; both scripts must refuse on the same conditions.

DB_TYPES_TARGETS=(SwimSyncApp/lib/database.types.ts SwimSyncAdmin/lib/database.types.ts)

# The version pinned in ci.yml's `supabase/setup-cli` step (and ui-drivers.yml must agree).
db_types_pinned_cli() {
  local root=$1 f v
  local seen=""
  for f in "$root/.github/workflows/ci.yml" "$root/.github/workflows/ui-drivers.yml"; do
    v=$(awk '/uses: supabase\/setup-cli@/ {grab=1; next} grab && /version:/ {print $2; exit}' "$f")
    [[ -n "$v" ]] || { echo "✗ no supabase/setup-cli version pin in ${f#"$root"/}" >&2; return 2; }
    if [[ -n "$seen" && "$v" != "$seen" ]]; then
      echo "✗ CLI pins disagree: ci.yml=$seen ui-drivers.yml=$v — keep them equal" >&2; return 2
    fi
    seen=$v
  done
  echo "$seen"
}

db_types_local_cli() { supabase --version 2>/dev/null | tr -d '[:space:]'; }

# Exit 1 with both versions printed when the local CLI is not the pinned one.
db_types_require_cli() {
  local root=$1 pinned local_v
  pinned=$(db_types_pinned_cli "$root") || return 2
  local_v=$(db_types_local_cli)
  if [[ "$local_v" != "$pinned" ]]; then
    echo "✗ Supabase CLI mismatch: local ${local_v:-<none>} · pinned in ci.yml $pinned" >&2
    echo "  Generated types differ between CLI versions. Install $pinned, or bump the pin" >&2
    echo "  in BOTH workflows together with a regen (never below what CI last ran green on)." >&2
    return 1
  fi
}

db_types_container() {
  local root=$1 id
  id=$(awk -F'"' '/^project_id *=/ {print $2; exit}' "$root/supabase/config.toml")
  echo "supabase_db_${id}"
}

# Exit 1 when the stack is down, or the applied migration set ≠ this checkout's.
db_types_require_migration_sync() {
  local root=$1 container applied ours
  container=$(db_types_container "$root")
  if ! applied=$(docker exec "$container" psql -U postgres -d postgres -At \
      -c "select version from supabase_migrations.schema_migrations order by 1" 2>/dev/null); then
    echo "✗ local Supabase stack is not reachable ($container) — run \`supabase start\`" >&2
    return 1
  fi
  ours=$(cd "$root/supabase/migrations" && ls -1 -- *.sql | sed -E 's/_.*//' | sort)
  if [[ "$applied" != "$ours" ]]; then
    echo "✗ the local DB's migrations ≠ this checkout's supabase/migrations (§7.347)" >&2
    echo "  applied locally, not in this checkout:" >&2
    comm -23 <(echo "$applied") <(echo "$ours") | sed 's/^/    /' >&2
    echo "  in this checkout, not applied locally:" >&2
    comm -13 <(echo "$applied") <(echo "$ours") | sed 's/^/    /' >&2
    echo "  Types from this DB would not describe this checkout (or prod). Sync first." >&2
    return 1
  fi
}

# Writes the generated file to $2. The header is part of generation, not an edit.
db_types_generate() {
  local root=$1 out=$2 err
  err=$(mktemp)
  {
    echo "// GENERATED by scripts/gen-db-types.sh from the local DB (supabase gen types"
    echo "// typescript --local --schema public). NEVER hand-edit: narrowing and widening live"
    echo "// in lib/database.overrides.ts. A migration that changes the public schema"
    echo "// regenerates this file in the same commit (G5, CI). Import it with \`import type\`"
    echo "// only (G6) — it exports a runtime \`Constants\` object."
    (cd "$root" && supabase gen types typescript --local --schema public 2>"$err")
  } >"$out" || { cat "$err" >&2; rm -f "$err"; return 1; }
  rm -f "$err"
  grep -q '^export type Database = ' "$out" || { echo "✗ gen types produced no Database type" >&2; return 1; }
}
